### ISSUE TITLE
Fatal error. Compatibility issue.

### ISSUE THREAD

**Issue by cam-spacebar** [sparticus1701/Q2A-Email-Notifications#1]
I installed this app to Q2A and got a fatal error:

"Warning: require_once(C:/wamp/www/q2a/qa-include/qa-util-emailer.php): failed to open stream: No such file or directory in C:\wamp\www\q2a\qa-plugin\email-notifications\email-notifications-event.php on line 18"

The error screenshot:
https://dl.dropbox.com/u/14276495/2012-07-08%20-%20Q2A%20plugin%20error/email-notification-error.jpg

I found out that "qa-util-emailer.php" appears to be deprecated - as seen in this thread:
http://www.question2answer.org/qa/15249/what-can-be-used-in-place-of-qa-util-emailer-php

This error is quite fatal to the operation of the Q2A platform as a whole.
# 
# MY DEV CONFIG

WAMP 2.2
Q2A 1.5.2

**Comment by sparticus1701** [comment]
We're aware of the problem and have not yet had time to fix it.

# 

Walter Williams
Senior Software Engineer
Sawtooth Software, Inc.

---

"Do, or do not.  There is no try."

-----Original Message-----
From: cameron burns [mailto:reply@reply.github.com] 
Sent: Saturday, July 07, 2012 8:39 AM
To: sawtoothsoftware
Subject: [Q2A-Email-Notifications] Fatal error. Compatibility issue. (#1)

I installed this app to Q2A and got a fatal error:

"Warning: require_once(C:/wamp/www/q2a/qa-include/qa-util-emailer.php): failed to open stream: No such file or directory in C:\wamp\www\q2a\qa-plugin\email-notifications\email-notifications-event.php on line 18"

The error screenshot:
https://dl.dropbox.com/u/14276495/2012-07-08%20-%20Q2A%20plugin%20error/email-notification-error.jpg

I found out that "qa-util-emailer.php" appears to be deprecated - as seen in this thread:
http://www.question2answer.org/qa/15249/what-can-be-used-in-place-of-qa-util-emailer-php

This error is quite fatal to the operation of the Q2A platform as a whole.

# 

# MY DEV CONFIG

WAMP 2.2
Q2A 1.5.2

---

Reply to this email directly or view it on GitHub:
https://github.com/sawtoothsoftware/Q2A-Email-Notifications/issues/1

**Comment by sparticus1701** [comment]
The code has been updated to work with Q2A 1.5.2.
