### ISSUE TITLE
Incorrect URL for "User Email Notifications" page.

### ISSUE THREAD

**Issue by madzim** [sparticus1701/Q2A-Email-Notifications#2]
The "User Email Notifications" link is correctly showing in the footer of the page. When I click the link I get an 404.

The root problem seems to be that the URL to the page is not being built correctly.

In my admin settings, I'm using the third URL structure (it is the first flagged with [OK]).

For context, the URL for the "All Activity" tab is:
     http://localhost:8090/?qa=activity

When I click the User Email Notification click, I'm taken to the url
     http://localhost:8090/qa-user-email-notifications-page

If I manually change the URL to include the "?qa=" before the page name, the page loads correctly.

Thanks
Curtis

**Comment by sparticus1701** [comment]
I designed the plugin to work with the URL structure (on the General tab) to use the first option, which is best for SEO.  You may be using the 3rd or 4th option, which I did not test.

If you can figure out how to modify the code to handle more cases, let me know.

**Comment by madzim** [comment]
For now, I went with the path of least residence and setup my Apache to use htaccess so that I could use the first option.
